### ISSUE TITLE
Job-UI: Create,Edit and Schedule

### ISSUE THREAD

**Issue by 0einstein0** [inveniosoftware/invenio-jobs#23]
# List View
![Image](https://github.com/inveniosoftware/invenio-jobs/assets/51617644/5e2fa828-3659-40c5-8955-b03e1c893429)

# Create View
![Image](https://github.com/inveniosoftware/invenio-jobs/assets/51617644/91f99ead-7d31-49fb-af7e-ef643a361d89)

# Edit View
![Image](https://github.com/inveniosoftware/invenio-jobs/assets/51617644/d4d8867b-db90-4061-8c8e-b26245068a13)

# Schedule Interval View
![Screenshot 2024-06-13 at 15 57 40](https://github.com/inveniosoftware/invenio-jobs/assets/51617644/20e0e496-5f55-4f2f-ab52-b4e7dfe7e2ad)

# Schedule Crontab View
![Screenshot 2024-06-13 at 15 57 46](https://github.com/inveniosoftware/invenio-jobs/assets/51617644/066e4997-4eb8-483e-8a6e-9505dcc51246)

**Comment by carlinmack** [comment]
the ordering of the crontab view inputs seems odd to me?

**Comment by 0einstein0** [comment]
> the ordering of the schedule inputs seems odd to me?

it's alphabetically sorted by default for now :)
