### ISSUE TITLE
UI: args form not loading correctly creating run from runs page

### ISSUE THREAD

**Issue by yashlamba** [inveniosoftware/invenio-jobs#58]
`Jobs list page -> Run Now`: https://127.0.0.1:5000/administration/jobs?q=&l=list&p=1&s=10&sort=title
![image](https://github.com/user-attachments/assets/11605c7d-5fa6-4144-9ad3-9c09b334e2db)

`Runs list page -> Run Now`: https://127.0.0.1:5000/administration/jobs/xyzjob?q=&l=list&p=1&s=10&sort=created
![image](https://github.com/user-attachments/assets/623a91f4-d726-4ffe-9dba-0bed6144d2d8)

**Comment by ntarocco** [comment]
As a workaround, we have removed the buttons in the runs list.
